[package]
name = "a4native"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = "0.21.1"
num = "0.4.3"
anyhow = "1.0.98"
time = { version = "0.3.41", features = ["formatting", "parsing"] }
